name: Despliegue de Portafolio

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

env:
  DEPLOY_BASE_URL: ${{ secrets.DEPLOY_BASE_URL }}

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy: 
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.url }}

    runs-on: ubuntu-latest
    steps: 
      - name: Clonar repositorio
        uses: actions/checkout@v4  # Correcta versión de la acción

      - name: Setup NodeJS
        uses: actions/setup-node@v4  # Correcta versión de la acción
        with:
          node-version: '20'
          cache: 'npm'

      - name: Instalar Dependencias
        run: npm install

      - name: Verificar variables de ambiente
        run: echo "DEPLOY_BASE_URL $DEPLOY_BASE_URL"

      - name: Compilar Proyecto
        run: npm run build

      - name: Configuración de GitHub Pages
        uses: actions/configure-pages@v3  # Correcta versión de la acción

      - name: Subir Compilado a GitHub
        uses: actions/upload-pages-artifact@v3  # Correcta versión de la acción
        with:
          path: './dist'  # Asegúrate de que la carpeta de compilación sea 'dist' o la que corresponda

      - name: Publicar Página
        id: deployment
        uses: actions/deploy-pages@v4  # Correcta versión de la acción
